name: heroku workflow

on: 
  push:
    branches:
      - master
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Set on JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with maven
        run: mvn -B package -DskipTests

      - name: Ejecucion Test Unitarios
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

      - name: Ejecucion Test API REST
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
      
      - name: Ejecucion Test Selenum
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/*.jar
          retention-days: 1
      
  #Ejecucion_test:
  #  name: ejecutar Test Unitarios y API REST
  #  runs-on: ubuntu-20.04
  #  needs: [build]
  #  steps: 
  #    - name: Ejecucion Test Unitarios
  #      run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

  #    - name: Ejecucion Test API REST
  #      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
      
  #    - name: Ejecucion Test Selenum
  #      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
    

  publish_in_heroku_registry:
    name: Publish in Heroku Registry
    runs-on: ubuntu-20.04
    needs: [build]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download Jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Build Docker Image
        run: docker build -t p .
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Change image name to point to Heroku registry
        run: docker tag p registry.heroku.com/$HEROKU_APP/web
      - name: Login in Heroku container registry
        run: heroku container:login
      - name: Push image to Heroku Registry
        run: docker push registry.heroku.com/$HEROKU_APP/web

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [publish_in_heroku_registry]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login in Heroku
        run: heroku container:login
      - name: Deploy to Heroku
        run: heroku container:release web

  ejecutando_smoke_test:
    name: Smoke test
    runs-on: ubuntu-latest
    needs: [deploy_to_heroku]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Ejecucion de test Selenium
        run: mvn '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' -DHost="https://ais-extraordinaria.herokuapp.com/" test
      - name: Ejecucionde test API REST
        run: mvn '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' -DHost="https://ais-extraordinaria.herokuapp.com/" test