name: por la noche

on: 
#  schedule:
#    - cron: '47 5,17 * * *'
  push:
    branches:
      master    
    
jobs:

  build:
    runs-on:  ubuntu-20.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Set on JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with maven
        run: mvn -B package -DskipTests

      - name: Ejecucion Test Unitarios
        run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

      - name: Ejecucion Test API REST
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
      
      - name: Ejecucion Test Selenum
        run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/*.jar
          retention-days: 1
  #Ejecucion_test:
  #  name: ejecutar Test Unitarios y API REST

  #  runs-on: ubuntu-20.04
  #  needs: [build]
  #  steps: 
  #    - name: Ejecucion Test Unitarios
  #      run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test

  #    - name: Ejecucion Test API REST
  #      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
      
  #    - name: Ejecucion Test Selenum
  #      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
        
  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download Jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d')
        id: project
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dev-${{ steps.project.outputs.tag }} .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev-${{ steps.project.outputs.tag }}